name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # runs weekly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run OpenSSF Scorecard"
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif

      - name: "Upload Scorecard SARIF file to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
name: OpenSSF Scorecard

on:
  branch_protection_rule:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # runs weekly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run OpenSSF Scorecard"
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif

      - name: "Upload Scorecard SARIF file to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

